# ░█████╗░██████╗░███████╗░█████╗░████████╗███████╗██████╗░  ██████╗░██╗░░░██╗  ██████╗░███████╗██╗░░░██╗████████╗███████╗░█████╗░
# ██╔══██╗██╔══██╗██╔════╝██╔══██╗╚══██╔══╝██╔════╝██╔══██╗  ██╔══██╗╚██╗░██╔╝  ██╔══██╗██╔════╝██║░░░██║╚══██╔══╝██╔════╝██╔══██╗
# ██║░░╚═╝██████╔╝█████╗░░███████║░░░██║░░░█████╗░░██║░░██║  ██████╦╝░╚████╔╝░  ██║░░██║█████╗░░╚██╗░██╔╝░░░██║░░░█████╗░░██║░░╚═╝
# ██║░░██╗██╔══██╗██╔══╝░░██╔══██║░░░██║░░░██╔══╝░░██║░░██║  ██╔══██╗░░╚██╔╝░░  ██║░░██║██╔══╝░░░╚████╔╝░░░░██║░░░██╔══╝░░██║░░██╗
# ╚█████╔╝██║░░██║███████╗██║░░██║░░░██║░░░███████╗██████╔╝  ██████╦╝░░░██║░░░  ██████╔╝███████╗░░╚██╔╝░░░░░██║░░░███████╗╚█████╔╝
# ░╚════╝░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝░░░╚═╝░░░╚══════╝╚═════╝░  ╚═════╝░░░░╚═╝░░░  ╚═════╝░╚══════╝░░░╚═╝░░░░░░╚═╝░░░╚══════╝░╚════╝░
#
# Links:
#  Github: https://github.com/TheDevTec/AmazingFishing
#  Discord: https://discord.io/spigotdevtec


# All translation files can be found in plugins/AmazingFishing/Translations folder
# You can create new files. New file need to be .yml type!
translation_file: "en"

options:
  # If Fishing points should be enabled. Player can use Points in shop.
  # PointsManager types: VAULT, POINTS
  # VAULT - If some Economy is active plugin will use money instead of points...
  fishingPoints: "POINTS"

fishing:
  # Default fishing permissions
  permissions: 
    fish: "amazingfishing.fishing"
    # If you want different default permission to be able to catch junk items
    junk: "amazingfishing.fishing"

# Command settings  
command:
  cmds:
  - "amazingfishing"
  - "fish"
  - "af"
  permissions:
    # cmd is default command permission ( /fish)
    cmd: "amazingfishing.command"
    open: "amazingfishing.command" # /fish open <menu>
    openOthers: "amazingfishing.command.openOthers" # /fish open <menu> <player>
    points_get: "amazingfishing.points.get" # /fish points get (player)
    points_add: "amazingfishing.points.add"
    points_remove: "amazingfishing.points.points_remove"
  # Here you can edit all help messages for each subcommand
  help:
    cmd: "&3/fish &f&l- &bOpens main menu" 
    open: "&3/fish open <menu> &f&l - &bOpens specific menu"
    openOthers: "&3/fish open <menu> <player> &f&l- &bOpens specific menu for specific player"
    points_get: "&3/fish points get (player) &f&l- &bGets players points"
    points_add: "&3/fish points add <player> <amount> &f&l- &bAdd points to a player"
    points_remove: "&3/fish points remove <player> <amount> &f&l- &bRemove points from a player"
  
# Shop settings
shop:
  # If player should get any money, points or XP from selling fishing items
  disableMoney: false
  disablePoints: true
  disableXp: false