# ░█████╗░██████╗░███████╗░█████╗░████████╗███████╗██████╗░  ██████╗░██╗░░░██╗  ██████╗░███████╗██╗░░░██╗████████╗███████╗░█████╗░
# ██╔══██╗██╔══██╗██╔════╝██╔══██╗╚══██╔══╝██╔════╝██╔══██╗  ██╔══██╗╚██╗░██╔╝  ██╔══██╗██╔════╝██║░░░██║╚══██╔══╝██╔════╝██╔══██╗
# ██║░░╚═╝██████╔╝█████╗░░███████║░░░██║░░░█████╗░░██║░░██║  ██████╦╝░╚████╔╝░  ██║░░██║█████╗░░╚██╗░██╔╝░░░██║░░░█████╗░░██║░░╚═╝
# ██║░░██╗██╔══██╗██╔══╝░░██╔══██║░░░██║░░░██╔══╝░░██║░░██║  ██╔══██╗░░╚██╔╝░░  ██║░░██║██╔══╝░░░╚████╔╝░░░░██║░░░██╔══╝░░██║░░██╗
# ╚█████╔╝██║░░██║███████╗██║░░██║░░░██║░░░███████╗██████╔╝  ██████╦╝░░░██║░░░  ██████╔╝███████╗░░╚██╔╝░░░░░██║░░░███████╗╚█████╔╝
# ░╚════╝░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝░░░╚═╝░░░╚══════╝╚═════╝░  ╚═════╝░░░░╚═╝░░░  ╚═════╝░╚══════╝░░░╚═╝░░░░░░╚═╝░░░╚══════╝░╚════╝░
#
# Links:
#  Github: https://github.com/TheDevTec/AmazingFishing
#  Discord: https://discord.io/spigotdevtec

Options:
  # PointsManager types: VAULT, USER
  PointsManager: "User"
  Calculator:
      # Default money calculation: (%length% / 4 +%weight% / 4 + %money%) * %bonus%
      # Default points calculation: (%length% / 4 +%weight% / 4 + %points%) * %bonus%
      # Default xp calculation: (%length% / 5 +%weight% / 5 + %experiences%) * %bonus%
      # Default weight calculation: (%length%-(%minweight%/%minlength%))/(%weight%/%maxlength%)
    weight: "(%length%-(%minweight%/%minlength%))/(%weight%/%maxlength%)"
    money: "(%length% / 4 +%weight% / 4 + %money%) * %bonus%"
    exps: "(%length% / 4 +%weight% / 4 + %experiences%) * %bonus%"
    points: "(%length% / 5 +%weight% / 5 + %points%) * %bonus%"
    
  Shop:
    Enabled: true
    SellFish: true
    Sounds:
      Shop-BuyItem: true

  Sell:
    DisableMoney: false
    DisableXP: false
    DisablePoints: false

  Bag:
    Enabled: true
    # Locations: DATA, SQL
    SaveLocation: "DATA"
    MySQL:
      Host: "localhost"
      Database: "global"
      Username: "admin"
      Password: "admin"
    OpenShop: true
    # If you want to be able to sell fish from your bag you need to set 'SellFish' to true
    SellFish: true
  Enchants:
    Enabled: true
    
# Preview text on click on fish in index
Preview:
- "&7Your records:"
- "&7 Highest weight: &b%weight%"
- "&7 Longest length: &b%length%"
- "&7 Total caught: &b%caught%"

# Tournaments:
Tournament:
  Type:
    Amount:
      Name: "&bAmount"
    Length:
      Name: "&bLength"
    Weight:
      Name: "&9Weight"
    TotalLength:
      Name: "&3TotalLength"
    TotalWeight:
      Name: "&3TotalWeight"
    Random:
      Name: "&6Random"