  # FISH
fish:
  # cod, tropical_fish, pufferfish, salmon
  cod:
    1:
      name: "&eCarp"
      # model: 1
      chance: 50.0
      # permission: String
      # Lore placeholders: %length%, %weight%, %chance%, %name%, %biomes%, %biome%, %x%, %y%, %z%, %world%
      # Other placeholders: %player% - just players name, %displayname% - Players display name
      lore:
      - "&7Weight: &f%weight%"
      - "&7Length: &f%length%"
      - "&7Chance: &f%chance%"
      - "&7Caught by: &f%displayname%"
      - "&7Caught in biome: &f%biome%"
      - "&7Caught on location: &f%x% %y% %z% %world%"
      messages:
        catch:
        - "&eYou catch %name% fish!"
        - "&eFish is &6%length% cm&e long and weighs &6%weight% kg"
        eat:
        - "&eYou ate %name% fish!"
      # commands:
        # catch: List
        # eat: List
      # biomes:
      # - <biome name>
      catch:
        # Types: DAY | NIGHT | EVERY
        time: EVERY
        # Types: SUN | RAIN | THUNDER | EVERY
        weather: EVERY
      weight: 45.5
      length: 80.7
      minweigth: 5.5
      minlength: 8.7
      money: 5.5
      points: 5.5
      xp: 10.5
      # calculator:
        # money: "(%length% / 4 +%weight% / 4 + %money%) * %bonus%"
        # exps: "(%length% / 4 +%weight% / 4 + %experiences%) * %bonus%"
        # points: "(%length% / 5 +%weight% / 5 + %points%) * %bonus%"
        # weigth: "(%length%-(%minweight%/%minlength%))/(%maxweight%/%maxlength%)"
      
  # ENCHANTMENTS
enchantments:
  example:
    name: "&eGreat enchant!"
    maxlevel: 10
    cost: 5
    bonus:
      chance: 5
      amount: 2
    # Description placeholders: %cost%, %maxlevel%, %name%, %displayname% - custom name with colors, %chance%, %amount%
    description:
    - "&eGreat enchant is great!"
    - "&7Bonus chance: %chance%"
    - "&7Bonus amount: %amount%"
    - "&7"
    - "&3Cost: &b%cost% points"

  # TREASURES
treasures:
  common:
    name: "&7Common treasure"
    # Placeholders: %player%, %chance%, %name% - 'common', %displayname% - custom treasure name, %biomes%, %biome%, %x%, %y%, %z%, %world%
    messages:
    - "&3You found &7Common treasure on &b%x% %y% %z% %world%&3!!"
    commands:
    - "eco give %player% 500"
    chance: 70.5
    # permission: String
    # biomes:
    # - <biome_name>
    catch:
      # Types: DAY | NIGHT | EVERY
      time: EVERY
      # Types: SUN | RAIN | THUNDER | EVERY
      weather: EVERY
  # Quests
quests:
  common:
    name: "&6&lSuperQuest"
    icon: "STONE"
    description:
    - "&6Great super duper quest"
    - "&7"
    - "&7Left click to accept quest"
    - "&7Right click to cancel quest (if it is in progress)"
    start:
      # commands:
      # - "say You are the best hero!"
      messages:
      - "&6You have started quest %questname%"
      - "&6Now you need to catch &e3x &eCarp"
    stages:
      1:
      # Placeholders: %player%, %quest% (common), %questname% (&6&lSuperQuest)
        commands:
        - "pay %player% 500"
        messages:
        - "%prefix% &6You have finished first stage of quest %questname%"
        # Action: catch_fish, eat_fish, sell_fish
        action: "catch_fish"
        # Value: type_of_fish.name_of_fish -> cod.<name> -> cod.1
        value: "cod.1"
        count: 3
      2:
        commands:
        - "say Congratulation %player%!!"
        messages:
        - "%prefix% &6You have finished second stage of quest %questname%"
        action: "eat_fish"
        value: "cod.1"
        count: 2
      3:
        commands:
        - "say Congrats %player%!!"
        messages:
        - "%prefix% &6You have finished quest %questname%"
        action: "sell_fish"
        value: "cod.1"
        count: 2