help:
  title: "&5Help"
  shop:
    displayName: "&bShop"
    type: GOLD_INGOT
    # types: BUY, SELL
    open: BUY
    # model: 0
    # lore: []
    # enchants: []
    # flags: []
    # unbreakable: false
  index:
    displayName: "&bIndex of fish"
    type: PAPER
  enchant:
    displayName: "&bEnchant table"
    # ENCHANTMENT_TABLE
    type: ENCHANTING_TABLE
  bag:
    displayName: "&bBag pack"
    type: CHEST
  quests:
    displayName: "&bQuests"
    type: ENCHANTED_BOOK
    enchants:
    - "UNBREAKING:1"
    flags:
    - "HIDE_ATTRIBUTES"
    - "HIDE_ENCHANTS"
  achievements:
    displayName: "&bAchievements"
    # DOUBLE_PLANT
    type: SUNFLOWER
  settings:
    displayName: "&bSettings"
    type: REDSTONE
  close:
    displayName: "&cLeave the help menu"
    # STAINED_GLASS_PANE:14
    type: RED_STAINED_GLASS_PANE

convertor:
  title: "&bConvertor"
  convert:
    displayName: "&bConvert fish to vanilla"
    type: LIME_STAINED_GLASS_PANE
  close:
    displayName: "&cLeave the convertor"
    # STAINED_GLASS_PANE:14
    type: RED_STAINED_GLASS_PANE
    
index:
  title: "&bIndex of fish"
  title-cod: "&bIndex of fish type &ncod"
  title-salmon: "&bIndex of fish type &nsalmon"
  title-pufferfish: "&bIndex of fish type &npufferfish"
  title-tropical_fish: "&bIndex of fish type &ntropical fish"
  title-junk: "&bIndex of &njunk"
  cod:
    displayName: "&bIndex of fish type &ncod"
    # RAW_FISH
    type: COD
  salmon:
    displayName: "&bIndex of fish type &nsalmon"
    # RAW_FISH:1
    type: SALMON
  pufferfish:
    displayName: "&bIndex of fish type &npufferfish"
    # RAW_FISH:2
    type: PUFFERFISH
  tropical_fish:
    displayName: "&bIndex of fish type &ntropical fish"
    # RAW_FISH:3
    type: TROPICAL_FISH
  junk:
    displayName: "&bIndex of &njunk"
    type: BUCKET
  close:
    displayName: "&cLeave the index"
    # STAINED_GLASS_PANE:14
    type: RED_STAINED_GLASS_PANE
    
shops:
  points:
    displayName: "&3%points% &bPoints"
    # DYE:4
    type: LAPIS_LAZULI
  convertor:
    displayName: "&bOpen the fish convertor"
    # RAW_FISH
    type: COD
  sell:
    title: "&eFish seller"
    bag:
      displayName: "&bBag"
      type: CHEST
      enchants:
      - "UNBREAKING"
      flags:
      - "HIDE_ATTRIBUTES"
      - "HIDE_ENCHANTS"
    buy-shop:
      displayName: "&bOpen the online store"
      type: EMERALD
      enchants:
      - "UNBREAKING"
      flags:
      - "HIDE_ATTRIBUTES"
      - "HIDE_ENCHANTS"
    sell:
      displayName: "&cClick to sell fish in the menu"
      type: GOLD_INGOT
    close:
      displayName: "&cLeave the seller"
      # STAINED_GLASS_PANE:14
      type: RED_STAINED_GLASS_PANE
  buy:
    title: "&eOnline store"
    bag:
      displayName: "&bBag"
      type: CHEST
      enchants:
      - "UNBREAKING"
      flags:
      - "HIDE_ATTRIBUTES"
      - "HIDE_ENCHANTS"
    sell-shop:
      displayName: "&bOpen fish seller"
      type: EMERALD
      enchants:
      - "UNBREAKING"
      flags:
      - "HIDE_ATTRIBUTES"
      - "HIDE_ENCHANTS"
    close:
      displayName: "&cLeave the store"
      # STAINED_GLASS_PANE:14
      type: RED_STAINED_GLASS_PANE

bag:
  title: "&eBag"
  sell:
    displayName: "&bSell all fish in the bag"
    type: GOLD_INGOT
  close:
    displayName: "&cLeave the bag"
    # STAINED_GLASS_PANE:14
    type: RED_STAINED_GLASS_PANE

enchant:
  title-select: "&bEnchant Table &7&l- &9Select fishing rod"
  title-add: "&bEnchant Table &7&l- &9Add/upgrade Enchant"
  points:
    displayName: "&3%points% &bPoints"
    # DYE:4
    type: LAPIS_LAZULI
  close:
    displayName: "&cLeave the enchant table"
    # STAINED_GLASS_PANE:14
    type: RED_STAINED_GLASS_PANE

settings:
  title: "&3Settings"
  records:
    on:
      displayName: "&aReceive records in the chat"
      # CONCRETE:13
      # For older version:
      # STAINED_GLASS_PANE:13
      type: GREEN_CONCRETE
      lore:
      - "&aYou are receiving fish record messages"
      - ""
      - "&7Click to turn it off"
    off:
      displayName: "&aReceive records in the chat"
      # CONCRETE:14
      # For older version:
      # STAINED_GLASS_PANE:14
      type: RED_CONCRETE
      lore:
      - "&cYou are not receiving fish record messages"
      - ""
      - "&7Click to turn it on"
  close:
    displayName: "&cLeave the settings"
    # STAINED_GLASS_PANE:14
    type: RED_STAINED_GLASS_PANE
    
quests:
  title: "&3All quests"
  title-category: "&3Quests &7- %category%"
  title-own: "&3My quests"
  own:
    displayName: "&bOpen my quests book"
    type: BOOK
  quest-progress:
  - "&7Quest progress:"
  - "&7   Stage: %stage%"
  - "&7   %action%: %now%&8/&7%total%"
  - "&7   Fish: %fish%"
  - "&7   Fish type: %type%"
  - "&7 "
  - "&7 Total stages: %stages_total%"
  close:
    displayName: "&cLeave the quests menu"
    # STAINED_GLASS_PANE:14
    type: RED_STAINED_GLASS_PANE

achievements:
  title: "&3Achievements"
  title-category: "&3Achievements &7&l- %category%"
  close:
    displayName: "&cLeave the achievements menu"
    # STAINED_GLASS_PANE:14
    type: RED_STAINED_GLASS_PANE

buttons:
  next:
    type: "PLAYER_HEAD"
    displaydisplayName: "&aNext page"
    head:
      type: "VALUES"
      owner: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmZmNTVmMWIzMmMzNDM1YWMxYWIzZTVlNTM1YzUwYjUyNzI4NWRhNzE2ZTU0ZmU3MDFjOWI1OTM1MmFmYzFjIn19fQ=="
  previous:
    type: "PLAYER_HEAD"
    displaydisplayName: "&6Previous page"
    head:
      type: "VALUES"
      owner: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjc2OGVkYzI4ODUzYzQyNDRkYmM2ZWViNjNiZDQ5ZWQ1NjhjYTIyYTg1MmEwYTU3OGIyZjJmOWZhYmU3MCJ9fX0="