help:
  title: "&5Help"
  shop:
    name: "&bShop"
    icon: GOLD_INGOT
    # types: BUY, SELL
    type: BUY
    # model: 0
    # lore: []
    # enchants: []
    # flags: []
    # unbreakable: false
  index:
    name: "&bIndex of fish"
    icon: PAPER
  enchant:
    name: "&bEnchant table"
    # ENCHANTMENT_TABLE
    icon: ENCHANTING_TABLE
  bag:
    name: "&bBag pack"
    icon: CHEST
  quests:
    name: "&bQuests"
    icon: BOOK
    enchants:
    - "UNBREAKING"
    flags:
    - "HIDE_ATTRIBUTES"
    - "HIDE_ENCHANTS"
  achievements:
    name: "&bAchievements"
    # DOUBLE_PLANT
    icon: SUNFLOWER
  settings:
    name: "&bSettings"
    icon: REDSTONE
  close:
    name: "&cLeave the help menu"
    # STAINED_GLASS_PANE:14
    icon: RED_STAINED_GLASS_PANE

convertor:
  title: "&bConvertor"
  convert:
    name: "&bConvert fish to vanilla"
    icon: LIME_STAINED_GLASS_PANE
  close:
    name: "&cLeave the convertor"
    # STAINED_GLASS_PANE:14
    icon: RED_STAINED_GLASS_PANE
    
index:
  title: "&bIndex of fish"
  title-cod: "&bIndex of fish type &ncod"
  title-salmon: "&bIndex of fish type &nsalmon"
  title-pufferfish: "&bIndex of fish type &npufferfish"
  title-tropical_fish: "&bIndex of fish type &ntropical fish"
  title-junk: "&bIndex of &njunk"
  cod:
    name: "&bIndex of fish type &ncod"
    # RAW_FISH
    icon: COD
  salmon:
    name: "&bIndex of fish type &nsalmon"
    # RAW_FISH:1
    icon: SALMON
  pufferfish:
    name: "&bIndex of fish type &npufferfish"
    # RAW_FISH:2
    icon: PUFFERFISH
  tropical_fish:
    name: "&bIndex of fish type &ntropical fish"
    # RAW_FISH:3
    icon: TROPICAL_FISH
  junk:
    name: "&bIndex of &njunk"
    icon: BUCKET
  close:
    name: "&cLeave the index"
    # STAINED_GLASS_PANE:14
    icon: RED_STAINED_GLASS_PANE
    
shops:
  points:
    name: "&3%points% &bPoints"
    # DYE:4
    icon: LAPIS_LAZULI
  convertor:
    name: "&bOpen the fish convertor"
    # RAW_FISH
    icon: COD
  sell:
    title: "&eFish seller"
    bag:
      name: "&bBag"
      icon: CHEST
      enchants:
      - "UNBREAKING"
      flags:
      - "HIDE_ATTRIBUTES"
      - "HIDE_ENCHANTS"
    buy-shop:
      name: "&bOpen the online store"
      icon: EMERALD
      enchants:
      - "UNBREAKING"
      flags:
      - "HIDE_ATTRIBUTES"
      - "HIDE_ENCHANTS"
    sell:
      name: "&cClick to sell fish in the menu"
      icon: GOLD_INGOT
    close:
      name: "&cLeave the seller"
      # STAINED_GLASS_PANE:14
      icon: RED_STAINED_GLASS_PANE
  buy:
    title: "&eOnline store"
    bag:
      name: "&bBag"
      icon: CHEST
      enchants:
      - "UNBREAKING"
      flags:
      - "HIDE_ATTRIBUTES"
      - "HIDE_ENCHANTS"
    sell-shop:
      name: "&bOpen fish seller"
      icon: EMERALD
      enchants:
      - "UNBREAKING"
      flags:
      - "HIDE_ATTRIBUTES"
      - "HIDE_ENCHANTS"
    close:
      name: "&cLeave the store"
      # STAINED_GLASS_PANE:14
      icon: RED_STAINED_GLASS_PANE

bag:
  title: "&eBag"
  sell:
    name: "&bSell all fish in the bag"
    icon: GOLD_INGOT
  close:
    name: "&cLeave the bag"
    # STAINED_GLASS_PANE:14
    icon: RED_STAINED_GLASS_PANE

enchant:
  title: "&bEnchant Table"
  title-select: "&bEnchant Table &7&l- &9Select fishing rod"
  title-add: "&bEnchant Table &7&l- &9Add Enchant"
  title-upgrade: "&bEnchant Table &7&l- &9Upgrade Enchant"
  add:
    name: "&9Add enchantment"
    # WORKBENCH
    icon: CRAFTING_TABLE
  upgrade:
    name: "&9Upgrade enchantment"
    icon: ANVIL
  points:
    name: "&3%points% &bPoints"
    # DYE:4
    icon: LAPIS_LAZULI
  close:
    name: "&cLeave the enchant table"
    # STAINED_GLASS_PANE:14
    icon: RED_STAINED_GLASS_PANE

settings:
  title: "&3Settings"
  records:
    on:
      name: "&aReceive records in the chat"
      # CONCRETE:13
      # For older version:
      # STAINED_GLASS_PANE:13
      icon: GREEN_CONCRETE
      lore:
      - "&aYou are receiving fish record messages"
      - ""
      - "&7Click to turn it off"
    off:
      name: "&aReceive records in the chat"
      # CONCRETE:14
      # For older version:
      # STAINED_GLASS_PANE:14
      icon: RED_CONCRETE
      lore:
      - "&cYou are not receiving fish record messages"
      - ""
      - "&7Click to turn it on"
  close:
    name: "&cLeave the settings"
    # STAINED_GLASS_PANE:14
    icon: RED_STAINED_GLASS_PANE
    
quests:
  title: "&3All quests"
  title-category: "&3Quests &7- %category%"
  title-own: "&3My quests"
  own:
    name: "&bOpen my quests book"
    icon: BOOK
  quest-progress:
  - "&7Quest progress:"
  - "&7   Stage: %stage%"
  - "&7   %action%: %now%&8/&7%total%"
  - "&7   Fish: %fish%"
  - "&7   Fish type: %type%"
  - "&7 "
  - "&7 Total stages: %stages_total%"
  close:
    name: "&cLeave the quests menu"
    # STAINED_GLASS_PANE:14
    icon: RED_STAINED_GLASS_PANE

achievements:
  title: "&3Achievements"
  title-category: "&3Achievements &7&l- %category%"
  close:
    name: "&cLeave the achievements menu"
    # STAINED_GLASS_PANE:14
    icon: RED_STAINED_GLASS_PANE

buttons:
  next:
    name: "&aNext page"
    icon: "head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmZmNTVmMWIzMmMzNDM1YWMxYWIzZTVlNTM1YzUwYjUyNzI4NWRhNzE2ZTU0ZmU3MDFjOWI1OTM1MmFmYzFjIn19fQ=="
  previous:
    name: "&6Previous page"
    icon: "head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjc2OGVkYzI4ODUzYzQyNDRkYmM2ZWViNjNiZDQ5ZWQ1NjhjYTIyYTg1MmEwYTU3OGIyZjJmOWZhYmU3MCJ9fX0="