GUI:
  Help:
    Player:
       Title: "&5Help &7- &4 Player"
       Shop: "&bShop"
       Stats: "&bStats"
       List: "&bFish list"
       Enchant: "&bEnchant table"
       Bag: "&bBackPack"
       Quests: "&bQuests"
       Achievements: "&bAchievements"
       Info: "&ePlayer section"
       Settings: "&bSettings"
    Admin:
      Title: "&5Help &7- &4 Admin"
      Info: "&cAdmin section"
      Reload: "&6Reload"
      Tournament: "&6Tournament"
      
  Convertor:
    Title: "&bConvertor"
  
  Index:
    Title: "&bIndex of fish"
    cod: "&bIndex of fish type &ncod"
    salmon: "&bIndex of fish type &nsalmon"
    tropical_fish: "&bIndex of fish type &ntropical fish"
    pufferfish: "&bIndex of fish type &npufferfish"
    junk: "&bList of junk items"
    Items:
      junk: "ENDER_CHEST"
  
  SellShop:
    Title: "&eSell Shop"
  BuyShop:
    Title: "&aBuy Shop"
  Bag:
    Title: "&eBag"
    Shop: "&aGo to shop"

  Enchant:
    Title: "&bEnchant Table"
    Add: "&9Add Enchant"
    Upgrade: "&9Upgrade"
    SelectRod_Title: "&bEnchant Table &7&l- &9Select fishing rod"
    Upgrade_Enchant_Title: "&bEnchant Table &7&l- &9Add Enchant"
    Add_Enchant_Title: "&bEnchant Table &7&l- &9Add Enchant"
  
  Tournaments:
    Title: "&2Tournaments"
    Stop:
      Title: "&4Stop &2Tournaments"
      Item: "&4Stop tournaments"
      StopOne:
        Name: "&4Stop one tournament"
        Description:
        - "&7 - Left click to stop tournament with prizes (in your world)"
        - "&7 - Right click to stop tournament without prizes (in your world)"
      StopAll:
        Name: "&4Stop all tournaments"
        Description:
        - "&7 - Left click to stop all tournaments with prizes"
        - "&7 - Right click to stop all tournaments without prizes"
    Start:
      Title: "&2Tournaments &7- &a %type%"
      Start: "&6Click to start new tournament"
      Description:
      - "&3> &5Type: %type%"
      - "&3> &5Time: %time%"
      
  Settings:
    Title: "&3Settings"
    SendRecords:
      on:
        Name: "&3Send records"
        Item: "GREEN_CONCRETE"
        Lore:
        - "&aYou are receiving new fish record messages"
        - "&7"
        - "&7Click to turn it off"
      off:
        Name: "&3Send records"
        Item: "RED_CONCRETE"
        Lore:
        - "&aYou are not receiving new fish record messages"
        - "&7"
        - "&7Click to turn it back on"
        
  Quests:
    Title:
      All: "&3All quests"
      Category: "&3Quests &7&l- %category%"
      MyQuests: "&3My quests"
    MyQuests: "&bGo to my quests"
    Quest_progress:
    - "&7Quest progress:"
    - "&7   Stage: %stage%"
    - "&7   %action%: %now%&8/&7%total%"
    - "&7   Fish: %fish%"
    - "&7   Fish type: %type%"
    - "&7 "
    - "&7 Total stages: %stages_total%"
    Quest_finished:
    - "&aQuest FINISHED"
    
  Achievements:
    Title: "&3Achievements"
    Category: "&3Achievements &7&l- %category%"
  
  Button:
    Next: "&aNext page"
    Next_Head: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmZmNTVmMWIzMmMzNDM1YWMxYWIzZTVlNTM1YzUwYjUyNzI4NWRhNzE2ZTU0ZmU3MDFjOWI1OTM1MmFmYzFjIn19fQ=="
    Previous: "&6Previous page"
    Previous_Head: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjc2OGVkYzI4ODUzYzQyNDRkYmM2ZWViNjNiZDQ5ZWQ1NjhjYTIyYTg1MmEwYTU3OGIyZjJmOWZhYmU3MCJ9fX0="