item1:
  enabled: true
  name: "&7TestingItem &e| %cost%"
  icon: "STONE"
  amount: 1
  lore: []
  cost:
    vault: 0
    points: 2
    exp: 0
  enchants: []
  flags: []
  unbreakable: false
  model: 0
  
  actions:
    commands:
    - "give %player% STONE 1"
    messages: []