items:
  snail:
    # Display name of item
    name: "&7Snail"
    
    # Model data of item (For custom resource pack)
    model: 1
    
    # Type of item -> type: "DIAMOND"
    type: "NAUTILUS_SHELL"
    
    # Head options: link, value, player's name (Houska02) or HeadDatabase head (hdb:ID)
    # head: ""
    
    # Chance to catch this item
    chance: 50.0
    
    # Remove this to catch fish without perms
    # permission: "amazingfishing.item.snail"
    
    # Lore placeholders: %weight%, %length%, %chance%, %name%, %biomes%, %biome%, %x%, %y%, %z%, %world%
    # Other placeholders: %player% - just players name, %displayname% - Players display name
    lore:
    - "&7Chance: &f%chance%"
    - "&7Caught by: &f%displayname%"
    - "&7Caught in biome: &f%biome%"
    - "&7Caught on location: &f%x% %y% %z% %world%"
    
    preview:
      # If you don't want item to be in Index GUI, just set show to false
      show: true
      name: "&7Snail"
      lore:
      - "&7Chance: &f%chance%"
      - "&7Catch:"
      - "&7 Time: &fEVERY"
      - "&7 Weather: &fEVERY"
      - "&7 Biomes: &fRIVER, FOREST"
      
    amount: 1
    
    # nbt:
    
    # enchants:
    # - "UNBREAKING:1"
    # flags:
    # - "HIDE_ENCHANTS"
    
    # A biomes in which item can be caught - empty list for every biome
    # List of biomes: 
    #  - (1.16) https://pastebin.com/9X5LRnSq
    #  - (1.12) https://pastebin.com/ejKGGq4D
    # biomes:
    # - "RIVER"
    # - "FOREST"
    # blockedbiomes:
    # - "DESERT"
    
    # The moment when the item can be caught (weather & time)
    catch:
      # Types: DAY | NIGHT | EVERY
      time: EVERY
      # Types: SUN | RAIN | THUNDER | EVERY
      weather: EVERY
      
    # List of messages on catch & eat
    messages:
      catch:
      - "&eYou catch %name% !"
      eat:
      - "&eYou ate %name%!"
     
    # List of commands on catch & eat
    commands:
      catch: []
      eat: []
    
    options:
      length: false
      weight: false
      eatable: false
      # Addhunger "value" adds hunger on eat
      addhunger: 2
      
    # * Stats *
    
    # Weight
    weight: 45.5
    minweigth: 5.5
    
    # Length
    length: 80.7
    minlength: 8.7
    
    # Custom calculator for weight - remove this calculaator to use global calculator from Config.yml
    calculator:
      weight: "-1"
      
      